// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChOA-N2jiqdy-zQ89spIp-A55rFjBiO64',
    appId: '1:919760503067:web:091738c38a3f1a1d0293be',
    messagingSenderId: '919760503067',
    projectId: 'tripify-d8e12',
    authDomain: 'tripify-d8e12.firebaseapp.com',
    storageBucket: 'tripify-d8e12.appspot.com',
    measurementId: 'G-DGGWWQ5M29',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiBpzgJ64rwySA4F4hLKJcwuTKnPVBcYU',
    appId: '1:919760503067:android:f7c8618d6362ac880293be',
    messagingSenderId: '919760503067',
    projectId: 'tripify-d8e12',
    storageBucket: 'tripify-d8e12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYAsqNWN0u-eCRiSmuaiKWJhUXperAxao',
    appId: '1:919760503067:ios:5bc90f3fc5f712e80293be',
    messagingSenderId: '919760503067',
    projectId: 'tripify-d8e12',
    storageBucket: 'tripify-d8e12.appspot.com',
    iosBundleId: 'com.example.tripify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYAsqNWN0u-eCRiSmuaiKWJhUXperAxao',
    appId: '1:919760503067:ios:5bc90f3fc5f712e80293be',
    messagingSenderId: '919760503067',
    projectId: 'tripify-d8e12',
    storageBucket: 'tripify-d8e12.appspot.com',
    iosBundleId: 'com.example.tripify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChOA-N2jiqdy-zQ89spIp-A55rFjBiO64',
    appId: '1:919760503067:web:27c19b908b043bf20293be',
    messagingSenderId: '919760503067',
    projectId: 'tripify-d8e12',
    authDomain: 'tripify-d8e12.firebaseapp.com',
    storageBucket: 'tripify-d8e12.appspot.com',
    measurementId: 'G-6XPWXE5GXY',
  );
}
